* Immotile

Build static sites using Emacs, org-mode and Clojure(script).

Heavily inspired by [[https://github.com/nakkaya/static][Static]].

Under development.

** Features
- [X] Convert org to html
- [X] Use Clojure code to generate templates using Hiccup
- [X] Watch and generate html files on changes
- [ ] Create a proper archive organizing post after date from org file
- [ ] Create Css from Clojure (Garden, CljsCss?)
- [X] Add support for Clojurescript
- [X] Reload the browser if any html changes (Figwheel?)
- [X] Actually use the config
- [ ] Move all configs to config.edn
- [ ] Spec the config
- [ ] Add init command

** Getting started
Create a project skeleton with the command:
#+BEGIN_SRC Shell
clj -Sdeps '{:deps
              {rpkarlsson/immotile
                {:git/url "https://github.com/rpkarlsson/immotile"
                 :sha "8fee341ac3c6c11a983f6808b18c26779c49b171"}}}' \
  -m immotile.core \
  init <my-project-name>
#+END_SRC

This will create a folder named my-project-name which has to be a valid
Clojure namespace.

To start immotile in development mode run the command:
#+BEGIN_SRC Shell
clj -A:dev
#+END_SRC

To build a production build run the command:
#+BEGIN_SRC shell
clj -A:build
#+END_SRC

** Options

   - Init <name> : Creates a project skeleton
   - dev         : Start immotile in development mode.
   - build-prod  : Compiles the source files using advanced optimizations.

** Examples

...

*** Bugs

...


** License

Copyright © 2018 Robin Karlssson

Distributed under the Eclipse Public License either version 1.0
