* Immotile

Build static sites using Emacs, org-mode and Clojure(script).

Heavily inspired by [[https://github.com/nakkaya/static][Static]].

Under development.

** Features
- [X] Convert org to html
- [X] Use Clojure code to generate templates using Hiccup
- [X] Watch and generate html files on changes
- [ ] Create a proper archive organizing post after date from org file
- [ ] Create Css from Clojure (Garden, CljsCss?)
- [X] Add support for Clojurescript
- [X] Reload the browser if any html changes (Figwheel?)
- [X] Actually use the config
- [ ] Move all configs to config.edn
- [ ] Spec the config
- [ ] Add init command

** Getting started
Create a project skeleton with the command:
#+BEGIN_SRC Shell
clj -J--add-modules -Jjava.xml.bind -m immotile.core init <MY PROJECT-NAME>
#+END_SRC

Feel free to drop the -J arguments if your not using Java 9.

To start immotile in development mode run the command:
#+BEGIN_SRC Shell
clj -J--add-modules -Jjava.xml.bind -m immotile.core dev
#+END_SRC

** Options

   - Init <name> : Creates a project skeleton
   - dev         : Start immotile in development mode.
   - build-prod  : Compiles the source files using advanced optimizations.

** Examples

...

*** Bugs

...


** License

Copyright © 2018 Robin Karlssson

Distributed under the Eclipse Public License either version 1.0
